### ISSUE TITLE
Sort labels from largest to smallest

### ISSUE THREAD

**Issue by styfle** [tipsy/github-profile-summary#13]
It would be nice if the labels were sorted so that the label with the most hits was at the top.

For example, I would expect to see TypeScript as number 1.
But this screenshot shows it at number 6:

![image](https://user-images.githubusercontent.com/229881/33954828-8d9c2e04-e007-11e7-9ec0-84389d43514a.png)

[source](https://github-profile-summary.com/user/styfle)

**Comment by tipsy** [comment]
I tried that first, but got comments on how it was nicer if the languages were in the same order/color for each language-chart. I guess it's not impossible to do both though, just requires a bit of work.

**Comment by styfle** [comment]
You could pick a color for a language in all charts and stick with it.
Maybe it would be more clear if you prefixed the label with a number such as:

1. TypeScript
2. JavaScript
3. HTML

That would indicate there was a sort or some sort of ordering was applied.

**Comment by tipsy** [comment]
> You could pick a color for a language in all charts and stick with it.

Yup, just need to write the code for it.

> Maybe it would be more clear if you prefixed the label with a number
> That would indicate there was a sort or some sort of ordering was applied.

If I add % to labels I don't think it'll be necessary.

**Comment by tipsy** [comment]
fixed: https://github-profile-summary.com/user/styfle

**Comment by styfle** [comment]
That was quick! Thanks! 👍🏼
