### ISSUE TITLE
find 20 unique colors somehow

### ISSUE THREAD

**Issue by tipsy** [tipsy/github-profile-summary#19]

**Comment by pkkummermo** [comment]
I use these personally, based on the journal in the comment underneath.

```
// A bunch of colors from http://epub.wu.ac.at/1692/1/document.pdf
const defaultColors = [
  "#023fa5",
  "#7d87b9",
  "#bec1d4",
  "#d6bcc0",
  "#bb7784",
  "#8e063b",
  "#4a6fe3",
  "#8595e1",
  "#b5bbe3",
  "#e6afb9",
  "#e07b91",
  "#d33f6a",
  "#11c638",
  "#8dd593",
  "#c6dec7",
  "#ead3c6",
  "#f0b98d",
  "#ef9708",
  "#0fcfc0",
  "#9cded6",
  "#d5eae7",
  "#f3e1eb",
  "#f6c4e1",
  "#f79cd4",
];
```

**Comment by MGaetan89** [comment]
Or you can use the one from Google's [Material Design](https://material.io/guidelines/style/color.html#color-color-palette).

**Comment by tipsy** [comment]
Material design wheel:
![image](https://user-images.githubusercontent.com/1521451/34135379-9a15caca-e460-11e7-8884-2b971277d558.png)

🤔

**Comment by tsjensen** [comment]
For best contrast, use the [Kelly Colors](https://gist.github.com/ollieglass/f6ddd781eeae1d24e391265432297538) 😉

**Comment by tipsy** [comment]
@tsjensen they don't look very nice though: 
![image](https://user-images.githubusercontent.com/1521451/34260020-b263298c-e664-11e7-8b4b-722bd3a7597c.png)

**Comment by tipsy** [comment]
Seems to work well enough with repeated colors.
