### ISSUE TITLE
[Question] Organizations Support

### ISSUE THREAD

**Issue by robertoestivill** [tipsy/github-profile-summary#23]
Does the project support organizations accounts instead of personal accounts?
I tried my organization both (hosted version, and locally running it) and it didn't work on neither of them.
Thanks

**Comment by tipsy** [comment]
It's being made with personal accounts in mind. I'm not sure how organizations could work for the hosted version, as you can't star using an org, and the rate-limit would be reached very fast if all orgs were allowed. A PR for allowing orgs locally would be fine though.

**Comment by pygy** [comment]
Another thing re. organizations, most of my recent OSS work has been made under orgs rather than in my own name, and what's displayed in my profile doesn't reflect that...

**Comment by tipsy** [comment]
I'll close this and keep #16
