### ISSUE TITLE
Consider replacing whens with ifs

### ISSUE THREAD

**Issue by rgilbert1** [tipsy/github-profile-summary#32]
Lemme preface real quick by saying I came across this little app and think it's pretty cool. I've been experimenting with Kotlin myself and have been loving it so far!

I was looking through your code and noticed that in `Main.kt` you use `when` switches for simple `true`/`false` values and thought they could be replaced with if conditions -- unless there is some particular reason for this decision.

For example,

```
when (UserCtrl.hasStarredRepo(user)) {
        true -> ctx.json(UserCtrl.getUserProfile(ctx.param("user")!!))
        false -> ctx.status(400)
}
```

could be

```
if (UserCtrl.hasStarredRepo(user)) ctx.json(UserCtrl.getUserProfile(user)) else ctx.status(400)
```

Just a suggestion, let me know what you think and if there is some particular reason for using `when`s here!

**Comment by tipsy** [comment]
> Lemme preface real quick by saying I came across this little app and think it's pretty cool. 

Thanks! I used to have an enum `{ STARRED, NOT_STARRED, NOT_FOUND }`, When I removed the enum I just left the `when`. 

I actually find:

```kotlin
when (UserCtrl.hasStarredRepo(user)) {
    true -> ctx.renderVelocity("user.vm", model("user", user))
    false -> ctx.redirect("/search?q=$user")
}
```

more readable than:

```kotlin 
if (UserCtrl.hasStarredRepo(user)) {
    ctx.renderVelocity("user.vm", model("user", user))
} else {
    ctx.redirect("/search?q=$user")
}
```

But I might be in the minority.

**Comment by rgilbert1** [comment]
Gotcha, makes sense.

**Comment by anonymous6936** [comment]
Close the issue

**Comment by anonymous6936** [comment]
our projects  ,issues, and improvements to our own projects should be freely shared to come together and build a project that fixes everyday issues..

**Comment by anonymous6936** [comment]
Ok

**Comment by MGaetan89** [comment]
What about?

```kotlin
when {
    UserCtrl.hasStarredRepo(user) -> ctx.renderVelocity("user.vm", model("user", user))
    else -> ctx.redirect("/search?q=$user")
}
```
