### ISSUE TITLE
Look up contributions

### ISSUE THREAD

**Issue by matejkramny** [tipsy/github-profile-summary#38]
First of all, good job! 👍 

If there's any room for improvement, I think it should also be pulling repositories the user contributes to or that the user is involved with.

I realise maybe the github API won't allow this or there are other logistical issues.

**Comment by tipsy** [comment]
Thanks. It's sort of being discussed in #16, with focus on organizations. Your question makes me wonder if we can use the event-api instead though, let me have a look.

**Comment by tipsy** [comment]
This approach might work: https://stackoverflow.com/a/37554614/7916291

**Comment by tipsy** [comment]
I'll close this in favor of #16, as it was created earlier.
