### ISSUE TITLE
consider trimming user input

### ISSUE THREAD

**Issue by dkfiresky** [tipsy/github-profile-summary#39]
https://github-profile-summary.com/

If you paste the username with spaaces in the end of the string, like ‘dkfiresky ‘, no profile will be found.

This is also issue for mobile devices, which use autocomplete to insert the username.

**Comment by tipsy** [comment]
Sure, will fix that.

**Comment by tipsy** [comment]
Thanks, fixed in f37ab189254db308b5d8c668fff9fabe295dbd96

**Comment by dkfiresky** [comment]
@tipsy thanks!
