### ISSUE TITLE
Not able to view my profile summary

### ISSUE THREAD

**Issue by thayumaanavan** [tipsy/github-profile-summary#40]
I'm getting below error when I enter my github username. Any setting needs to be configured in my profile?
As far as I know, my profile is public.

>Couldn't build profile for thayumaanavan
>If you are thayumaanavan, please star the repo and try again.

**Comment by tipsy** [comment]
You need to have the repo starred while your profile is being built, but nothing other than that. I can have a look locally later.

**Comment by thayumaanavan** [comment]
Yes. I missed doing that 👍
