### ISSUE TITLE
Use github colors for programming languages

### ISSUE THREAD

**Issue by mzgnr** [tipsy/github-profile-summary#44]
you can check this out https://github.com/ozh/github-colors/blob/master/colors.json

**Comment by tipsy** [comment]
Interesting. Thanks, will have a look.

**Comment by mzgnr** [comment]
I can work on a PR if its okay

**Comment by tipsy** [comment]
Sure, I won't promise to merge it though. I need to see how it looks/feels.

**Comment by tipsy** [comment]
I tried them and I don't like how they make the graphs look.
