### ISSUE TITLE
Doesn't find my username

### ISSUE THREAD

**Issue by sevdalin** [tipsy/github-profile-summary#46]
The App doesn't find my Github Username. What it the reason?

**Comment by tipsy** [comment]
Doesn't look like you have starred the repo. You have to star the repo before searching (you can unstar after your profile has been built).

**Comment by sevdalin** [comment]
Yes, it worked. Excuse me for the opened issue, I just didn't saw in the README.md that I need to like the Repo before I use it. Thanks!
