### ISSUE TITLE
Improve responsiveness for the generated profile

### ISSUE THREAD

**Issue by bharatramnani94** [tipsy/github-profile-summary#53]
![image](https://user-images.githubusercontent.com/7734410/34420340-08de959c-ec2f-11e7-8260-1ac00920a0e4.png)

As the above screenshot clearly shows, there's a scope for improvement of the look of the profile, particularly for the mobile view. Currently the graph isn't big enough to view when the list of labels increase.

**Comment by tipsy** [comment]
Hi @bharatramnani94. I haven't done anything to the responsiveness offered by chartsjs. If you have any suggestions, please feel free to create a PR.

**Comment by bharatramnani94** [comment]
Basically we need to [make the chart responsive](http://www.chartjs.org/docs/latest/general/responsive.html).
There are [options to change the legend position](http://www.chartjs.org/docs/latest/configuration/legend.html#position) (from left to bottom in our case). I think we need to check the width of the chart, and if it lies below a certain width (say 500px), we may update the position of the legend from right to bottom. Something like this:

![Shift legend to bottom for small screens](https://user-images.githubusercontent.com/7734410/34423015-49762e66-ec3f-11e7-81d7-82877137d92f.png)

I'm currently not in a situation to create a PR for this myself. I'll try to do that after few days.
