### ISSUE TITLE
Page won't refresh after first load?

### ISSUE THREAD

**Issue by Doofitator** [tipsy/github-profile-summary#54]
I'm new to Github, so I don't know if it's something I've done, but I put my username into this page when I only had one repo on one language - now I've got two, however the page hasn't uploaded with my other repo and language stats.

Is there a way to make it re-crawl my profile?

**Comment by tipsy** [comment]
Unfortunately you'll have to wait 24 hour. Your profile is cached, which is necessary because of the rate-limit. We could give each user a 'rebuild' counter and a couple of rebuilds id the number of remaining requests is high.

**Comment by Doofitator** [comment]
Awesome. Thanks for explaining why :)
