### ISSUE TITLE
Last item in the chart is of wrong year

### ISSUE THREAD

**Issue by sompylasar** [tipsy/github-profile-summary#61]
https://github-profile-summary.com/user/sompylasar

After 2018-Q1, expected 2018-Q2, got 2009-Q2.

<img width="205" alt="screen shot 2018-01-02 at 1 03 35 pm" src="https://user-images.githubusercontent.com/498274/34499929-600c42ec-efbd-11e7-8104-a1ed4f21f1ac.png">

<img width="248" alt="screen shot 2018-01-02 at 1 00 53 pm" src="https://user-images.githubusercontent.com/498274/34499920-508c1e00-efbd-11e7-9a12-0e5c47c18ed8.png">

**Comment by sompylasar** [comment]
The issue is that the data for the `lineChart` is not sorted.
https://github.com/tipsy/github-profile-summary/blob/a0232c561dc34d2570e64e1c86531405b4935734/src/main/resources/static/charts.js#L122-L129

```
Object.keys(data[objectName])
(31) ["2010-Q4", "2011-Q1", "2011-Q2", "2011-Q3", "2011-Q4", "2012-Q1", 
"2012-Q2", "2012-Q3", "2012-Q4", "2013-Q1", "2013-Q2", "2013-Q3", 
"2013-Q4", "2014-Q1", "2014-Q2", "2014-Q3", "2014-Q4", "2015-Q1", 
"2015-Q2", "2015-Q3", "2015-Q4", "2016-Q1", "2016-Q2", "2016-Q3", 
"2016-Q4", "2017-Q1", "2017-Q2", "2017-Q3", "2017-Q4", "2018-Q1", 
"2009-Q2"]
```

**Comment by iProdigy** [comment]
This is due to 00f96e2 where the call to create a sorted map has been replaced with `toMutableMap` in `CommitCountUtil#getCommitsForQuarters`

**Comment by tipsy** [comment]
Well, that's embarrassing.

**Comment by tipsy** [comment]
@sompylasar should be fixed now.

**Comment by sompylasar** [comment]
Verified fixed, thanks @tipsy 

<img width="805" alt="screen shot 2018-01-02 at 2 05 52 pm" src="https://user-images.githubusercontent.com/498274/34501951-19f25202-efc6-11e7-916e-2434f261ffaf.png">

**Comment by sompylasar** [comment]
FTR, fixing commit: https://github.com/tipsy/github-profile-summary/commit/d6d7d7e807af9c84530f60adcb68c51458f983f4
