### ISSUE TITLE
figure out what's wrong with the latest commits

### ISSUE THREAD

**Issue by tipsy** [tipsy/github-profile-summary#70]
@iProdigy app has been crashing a lot since the latest changes, so i reverted everything
i'll re-revert things one by one and try to pay closer attention

**Comment by iProdigy** [comment]
Strange - what are the crash logs looking like

**Comment by tipsy** [comment]
I've been a bit busy this weekend. Seems logs are limited to 1500 lines, so they are long gone.

**Comment by Misti26** [comment]
Payments

**Comment by tipsy** [comment]
Well said.

**Comment by tipsy** [comment]
I've re-reverted the commits one-by-one (prior to merging them), and everything seems to be working fine. Maybe it was Heroku itself having problems.
