### ISSUE TITLE
feature: Letting user force update of profile-summary once a day

### ISSUE THREAD

**Issue by exoji2e** [tipsy/github-profile-summary#72]
I starred and generated the summary about a week ago, however the summary has not been updated since then. 

It would be nice to be able to force an update once a day, so it's possible to see progress :)

**Comment by tipsy** [comment]
> I starred and generated the summary about a week ago, however the summary has not been updated since then.

Your profile is only cached for 6 hours before it is rebuilt. Maybe your activity is private, or belongs to an organization?

**Comment by exoji2e** [comment]
> or belongs to an organization?
Yes, right. #16 Closing.
