### ISSUE TITLE
Color double-ups?

### ISSUE THREAD

**Issue by Doofitator** [tipsy/github-profile-summary#73]
Not sure if this has already been addressed, however I noticed today that two repositories had been assigned the same color. Are you aware of this?
![screen shot](https://user-images.githubusercontent.com/4780013/35181072-347e83a0-fe0f-11e7-8c7c-2aa7964e7ae4.png)

**Comment by tipsy** [comment]
Yes, very aware. I was looking for more colors, but they are hard to find.

**Comment by Doofitator** [comment]
Haha fair enough. I'll let you work on it ;)

**Comment by Doofitator** [comment]
Haha fair enough. I'll let you work on it ;)

**Comment by Doofitator** [comment]
Haha fair enough. I'll let you work on it ;)

**Comment by tipsy** [comment]
More or less fixed by stealing the JS from @iProdigy's #74
