### ISSUE TITLE
Make www subdomain work on heroku

### ISSUE THREAD

**Issue by iProdigy** [tipsy/github-profile-summary#75]
https://www.github-profile-summary.com/ doesn't work while https://github-profile-summary.com/ does. This is somewhat annoying when I Ctrl-Enter the domain and the browser prepends the protocol and www.

Documentation from Heroku: https://support.dnsimple.com/articles/redirect-heroku/#redirect-https

**Comment by tipsy** [comment]
Fixed!

**Comment by tipsy** [comment]
Actually, I only fixed it for non-https. Fixing it for https looks like a lot more work...

**Comment by tipsy** [comment]
Seems the free cert from Heroku doesn't allow this.
